CREATE TABLE IF NOT EXISTS Admins (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Students (
  reg_no VARCHAR(50) PRIMARY KEY,
  student_name VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  class_name VARCHAR(100) NOT NULL,
  roll_number VARCHAR(50) NOT NULL,
  photo_url TEXT,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(20),
  date_of_birth VARCHAR(50),
  parent_name VARCHAR(255),
  parent_phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS StudentFees (
  id SERIAL PRIMARY KEY,
  reg_no VARCHAR(50) NOT NULL UNIQUE,
  student_name VARCHAR(255) NOT NULL,
  fee_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reg_no) REFERENCES Students(reg_no) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Notices (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Gallery (
  id SERIAL PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  image_url TEXT NOT NULL,
  caption VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Future tables for Phase 2
CREATE TABLE IF NOT EXISTS Roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Exams (
  id SERIAL PRIMARY KEY,
  exam_name VARCHAR(255) NOT NULL,
  exam_date VARCHAR(100) NOT NULL,
  total_marks INTEGER NOT NULL,
  passing_marks INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Hostels (
  id SERIAL PRIMARY KEY,
  hostel_name VARCHAR(255) NOT NULL,
  capacity INTEGER NOT NULL,
  warden_name VARCHAR(255) NOT NULL,
  contact_phone VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HostelAssignments (
  id SERIAL PRIMARY KEY,
  reg_no VARCHAR(50) NOT NULL,
  hostel_id INTEGER NOT NULL,
  room_number VARCHAR(50) NOT NULL,
  assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reg_no) REFERENCES Students(reg_no) ON DELETE CASCADE,
  FOREIGN KEY (hostel_id) REFERENCES Hostels(id)
);

CREATE TABLE IF NOT EXISTS PaymentTransactions (
  id SERIAL PRIMARY KEY,
  reg_no VARCHAR(50) NOT NULL,
  amount REAL NOT NULL,
  payment_date VARCHAR(100) NOT NULL,
  payment_method VARCHAR(100) NOT NULL,
  transaction_id VARCHAR(255) UNIQUE NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reg_no) REFERENCES Students(reg_no) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AuditLogs (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(255),
  action VARCHAR(255) NOT NULL,
  resource_type VARCHAR(255) NOT NULL,
  resource_id VARCHAR(255),
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
